hosts:
  - "172.26.2.109"
  - "172.26.2.110"
  - "172.26.2.111"
  - "172.26.2.112:8080"
tasks:
  - name: "Show all"
    cmd: "ls -a"
    out: true
  - name: "Install python3"
    cmd: "yum install -y python3"
  - name: "Check python3"
    cmd: "which python3"
    out: true
config:
  connection_timeout: 5000  # init connection timeout in ms